### PR TITLE
Support jump to definition functionality

### PR DESCRIPTION
**Pull request by ryu1kn**
* Support jump to definition functionality
* Ignored .vscode-test directory
* Removed files in `out` directory

Not tested on Windows 🙃

### CODE REVIEW

**Comment by ryu1kn** [comment]
This PR is for https://github.com/haskelly-dev/Haskelly/issues/33

**Comment by ryu1kn** [comment]
Any chances to review the PR @martrik ?

**Comment by martrik** [comment]
Hey @ryu1kn! Thanks for the PR, I'll have a look at it this weekend, but it seems that I'll be able to merge it right away. I've got one question though, do you have any idea on how to implement this also for external libraries?

**Comment by ryu1kn** [comment]
It would really depend on intero and I haven’t looked at it much. Sometimes jump to definition takes you to the source of external libraries under .stack-work directory. There might be some way to tell intero to look for definitions under certain directories like ~/.cabal or ~/.stack.

**Comment by martrik** [comment]
I see... I'll merge this then and we can later build on this feature.

**Comment by martrik** [comment]
I'll deploy the new version to the store in a couple of days :)

**Pull request merged**
